export class Country {
  countryList =[
    { label: "1", value: "Afghanistan","enShortName":"AF" },
    { label: "2", value: "Aland Islands","enShortName":"AX" },
    { label: "3", value: "Albania","enShortName":"AL" },
    { label: "4", value: "Algeria","enShortName":"DZ" },
    { label: "5", value: "American Samoa","enShortName":"AS" },
    { label: "6", value: "Andorra","enShortName":"AD" },
    { label: "7", value: "Angola","enShortName":"AO" },
    { label: "8", value: "Anguilla","enShortName":"AI" },
    { label: "9", value: "Antigua and Barbuda","enShortName":"AG" },
    { label: "10", value: "Argentina","enShortName":"AR" },
    { label: "11", value: "Armenia","enShortName":"AM" },
    { label: "12", value: "Aruba","enShortName":"AW"},
    { label: "13", value: "Australia","enShortName":"AU" },
    { label: "14", value: "Austria","enShortName":"AT" },
    { label: "15", value: "Azerbaijan", "enShortName": "AZ" },
    { label: "16", value: "Bangladesh", "enShortName": "BD" },
    { label: "17", value: "Bahrain", "enShortName": "BH" },
    { label: "18", value: "Bahamas", "enShortName": "BS" },
    { label: "19", value: "Barbados", "enShortName": "BB" },
    { label: "20", value: "Belarus", "enShortName": "BY" },
    { label: "21", value: "Belgium", "enShortName": "BE" },
    { label: "22", value: "Belize", "enShortName": "BZ" },
    { label: "23", value: "Benin", "enShortName": "BJ" },
    { label: "24", value: "Bermuda", "enShortName": "BM" },
    { label: "25", value: "Bhutan", "enShortName": "BT" },
    { label: "26", value: "Bolivia", "enShortName": "BO" },
    { label: "27", value: "Bosnia and Herzegovina", "enShortName": "BA" },
    { label: "28", value: "Botswana", "enShortName": "BW" },
    { label: "29", value: "Bouvet Island", "enShortName": "BV" },
    { label: "30", value: "Brazil", "enShortName": "BR" },
    { label: "31", value: "Brunei", "enShortName": "BN" },
    { label: "32", value: "Bulgaria", "enShortName": "BG" },
    { label: "33", value: "Burkina Faso", "enShortName": "BF" },
    { label: "34", value: "Burundi", "enShortName": "BI" },
    { label: "35", value: "Cambodia", "enShortName": "KH" },
    { label: "36", value: "Cameroon", "enShortName": "CM" },
    { label: "37", value: "Canada", "enShortName": "CA" },
    { label: "38", value: "Cape Verde", "enShortName": "CV" },
    { label: "39", value: "Central African Republic", "enShortName": "CF" },
    { label: "40", value: "Chad", "enShortName": "TD" },
    { label: "41", value: "Chile", "enShortName": "CL" },
    { label: "42", value: "Christmas Islands", "enShortName": "CX" },
    { label: "43", value: "Cocos (keeling) Islands", "enShortName": "CC" },
    { label: "44", value: "Colombia", "enShortName": "CO" },
    { label: "45", value: "Comoros", "enShortName": "KM" },
    { label: "46", value: "Congo (Congo-Kinshasa)", "enShortName": "CD" },
    { label: "47", value: "Congo", "enShortName": "CG" },
    { label: "48", value: "Cook Islands", "enShortName": "CK" },
    { label: "49", value: "Costa Rica", "enShortName": "CR" },
    { label: "50", value: "Cote D'Ivoire", "enShortName": "CI" },
    { label: "51", value: "China", "enShortName": "CN" },
    { label: "52", value: "Croatia", "enShortName": "HR" },
    { label: "53", value: "Cuba", "enShortName": "CU" },
    { label: "54", value: "Czech", "enShortName": "CZ" },
    { label: "55", value: "Cyprus", "enShortName": "CY" },
    { label: "56", value: "Denmark", "enShortName": "DK" },
    { label: "57", value: "Djibouti", "enShortName": "DJ" },
    { label: "58", value: "Dominica", "enShortName": "DM" },
    { label: "59", value: "East Timor", "enShortName": "" },
    { label: "60", value: "Ecuador", "enShortName": "EC" },
    { label: "61", value: "Egypt", "enShortName": "EG" },
    { label: "62", value: "Equatorial Guinea", "enShortName": "GQ" },
    { label: "63", value: "Eritrea", "enShortName": "ER" },
    { label: "64", value: "Estonia", "enShortName": "EE" },
    { label: "65", value: "Ethiopia", "enShortName": "ET" },
    { label: "66", value: "Faroe Islands", "enShortName": "FO" },
    { label: "67", value: "Fiji", "enShortName": "FJ" },
    { label: "68", value: "Finland", "enShortName": "FI" },
    { label: "69", value: "France", "enShortName": "FR" },
    { label: "70", value: "MetropolitanFrance", "enShortName": "FX" },
    { label: "71", value: "French Guiana", "enShortName": "GF" },
    { label: "72", value: "French Polynesia", "enShortName": "PF" },
    { label: "73", value: "Gabon", "enShortName": "GA" },
    { label: "74", value: "Gambia", "enShortName": "GM" },
    { label: "75", value: "Georgia", "enShortName": "GE" },
    { label: "76", value: "Germany", "enShortName": "DE" },
    { label: "77", value: "Ghana", "enShortName": "GH" },
    { label: "78", value: "Gibraltar", "enShortName": "GI" },
    { label: "79", value: "Greece", "enShortName": "GR" },
    { label: "80", value: "Grenada", "enShortName": "GD" },
    { label: "81", value: "Guadeloupe", "enShortName": "GP" },
    { label: "82", value: "Guam", "enShortName": "GU" },
    { label: "83", value: "Guatemala", "enShortName": "GT" },
    { label: "84", value: "Guernsey", "enShortName": "GG" },
    { label: "85", value: "Guinea-Bissau", "enShortName": "GW" },
    { label: "86", value: "Guinea", "enShortName": "GN" },
    { label: "87", value: "Guyana", "enShortName": "GY" },
    { label: "88", value: "Haiti", "enShortName": "HT" },
    { label: "89", value: "Honduras", "enShortName": "HN" },
    { label: "90", value: "Hungary", "enShortName": "HU" },
    { label: "91", value: "Iceland", "enShortName": "IS" },
    { label: "92", value: "India", "enShortName": "IN" },
    { label: "93", value: "Indonesia", "enShortName": "ID" },
    { label: "94", value: "Iran", "enShortName": "IR" },
    { label: "95", value: "Iraq", "enShortName": "IQ" },
    { label: "96", value: "Ireland", "enShortName": "IE" },
    { label: "97", value: "Isle of Man", "enShortName": "IM" },
    { label: "98", value: "Israel", "enShortName": "IL" },
    { label: "99", value: "Italy", "enShortName": "IT" },
    { label: "100", value: "Jamaica", "enShortName": "JM" },
    { label: "101", value: "Japan", "enShortName": "JP" },
    { label: "102", value: "Jersey", "enShortName": "JE" },
    { label: "103", value: "Jordan", "enShortName": "JO" },
    { label: "104", value: "Kazakhstan", "enShortName": "KZ" },
    { label: "105", value: "Kenya", "enShortName": "KE" },
    { label: "106", value: "Kiribati", "enShortName": "KI" },
    { label: "107", value: "Korea (South)", "enShortName": "KR" },
    { label: "108", value: "Korea (North)", "enShortName": "KD" },
    { label: "109", value: "Kuwait", "enShortName": "KW" },
    { label: "110", value: "Kyrgyzstan", "enShortName": "KG" },
    { label: "111", value: "Laos", "enShortName": "LO" },
    { label: "112", value: "Latvia", "enShortName": "LV" },
    { label: "113", value: "Lebanon", "enShortName": "LB" },
    { label: "114", value: "Lesotho", "enShortName": "LS" },
    { label: "115", value: "Liberia", "enShortName": "LR" },
    { label: "116", value: "Libya", "enShortName": "LY" },
    { label: "117", value: "Liechtenstein", "enShortName": "LI" },
    { label: "118", value: "Lithuania", "enShortName": "LT" },
    { label: "119", value: "Luxembourg", "enShortName": "LU" },
    { label: "120", value: "Macedonia", "enShortName": "MK" },
    { label: "121", value: "Malawi", "enShortName": "MW" },
    { label: "122", value: "Malaysia", "enShortName": "MY" },
    { label: "123", value: "Madagascar", "enShortName": "MG" },
    { label: "124", value: "Maldives", "enShortName": "MV" },
    { label: "125", value: "Mali", "enShortName": "ML" },
    { label: "126", value: "Malta", "enShortName": "MT" },
    { label: "127", value: "Marshall Islands", "enShortName": "MH" },
    { label: "128", value: "Martinique", "enShortName": "MQ" },
    { label: "129", value: "Mauritania", "enShortName": "MR" },
    { label: "130", value: "Mauritius", "enShortName": "MU" },
    { label: "131", value: "Mayotte", "enShortName": "YT" },
    { label: "132", value: "Mexico", "enShortName": "MX" },
    { label: "133", value: "Micronesia", "enShortName": "MF" },
    { label: "134", value: "Moldova", "enShortName": "MD" },
    { label: "135", value: "Monaco", "enShortName": "MC" },
    { label: "136", value: "Mongolia", "enShortName": "MN" },
    { label: "137", value: "Montenegro", "enShortName": "ME" },
    { label: "138", value: "Montserrat", "enShortName": "MS" },
    { label: "139", value: "Morocco", "enShortName": "MA" },
    { label: "140", value: "Mozambique", "enShortName": "MZ" },
    { label: "141", value: "Myanmar", "enShortName": "MM" },
    { label: "142", value: "Namibia", "enShortName": "NA" },
    { label: "143", value: "Nauru", "enShortName": "NR" },
    { label: "144", value: "Nepal", "enShortName": "NP" },
    { label: "145", value: "Netherlands", "enShortName": "NL" },
    { label: "146", value: "New Caledonia", "enShortName": "NC" },
    { label: "147", value: "New Zealand", "enShortName": "NZ" },
    { label: "148", value: "Nicaragua", "enShortName": "NI" },
    { label: "149", value: "Niger", "enShortName": "NE" },
    { label: "150", value: "Nigeria", "enShortName": "NG" },
    { label: "151", value: "Niue", "enShortName": "NU" },
    { label: "152", value: "Norfolk Island", "enShortName": "NF" },
    { label: "153", value: "Norway", "enShortName": "NO" },
    { label: "154", value: "Oman", "enShortName": "OM" },
    { label: "155", value: "Pakistan", "enShortName": "PK" },
    { label: "156", value: "Palau", "enShortName": "PW" },
    { label: "157", value: "Palestine", "enShortName": "PS" },
    { label: "158", value: "Panama", "enShortName": "PA" },
    { label: "159", value: "Papua New Guinea", "enShortName": "PG" },
    { label: "160", value: "Peru", "enShortName": "PE" },
    { label: "161", value: "Philippines", "enShortName": "PH" },
    { label: "162", value: "Pitcairn Islands", "enShortName": "PN" },
    { label: "163", value: "Poland", "enShortName": "PL" },
    { label: "164", value: "Portugal", "enShortName": "PT" },
    { label: "165", value: "Puerto Rico", "enShortName": "PR" },
    { label: "166", value: "Qatar", "enShortName": "QA" },
    { label: "167", value: "Reunion", "enShortName": "RE" },
    { label: "168", value: "Romania", "enShortName": "RO" },
    { label: "169", value: "Rwanda", "enShortName": "RW" },
    { label: "170", value: "Russian Federation", "enShortName": "RU" },
    { label: "171", value: "Saint Helena", "enShortName": "SH" },
    { label: "172", value: "Saint Kitts-Nevis", "enShortName": "KN" },
    { label: "173", value: "Saint Lucia", "enShortName": "LC" },
    { label: "174", value: "Saint Vincent and the Grenadines", "enShortName": "VG" },
    { label: "175", value: "El Salvador", "enShortName": "SV" },
    { label: "176", value: "Samoa", "enShortName": "WS" },
    { label: "177", value: "San Marino", "enShortName": "SM" },
    { label: "178", value: "Sao Tome and Principe", "enShortName": "ST" },
    { label: "179", value: "Saudi Arabia", "enShortName": "SA" },
    { label: "180", value: "Senegal", "enShortName": "SN" },
    { label: "181", value: "Seychelles", "enShortName": "SC" },
    { label: "182", value: "Sierra Leone", "enShortName": "SL" },
    { label: "183", value: "Singapore", "enShortName": "SG" },
    { label: "184", value: "Serbia", "enShortName": "RS" },
    { label: "185", value: "Slovakia", "enShortName": "SK" },
    { label: "186", value: "Slovenia", "enShortName": "SI" },
    { label: "187", value: "Solomon Islands", "enShortName": "SB" },
    { label: "188", value: "Somalia", "enShortName": "SO" },
    { label: "189", value: "South Africa", "enShortName": "ZA" },
    { label: "190", value: "Spain", "enShortName": "ES" },
    { label: "191", value: "Sri Lanka", "enShortName": "LK" },
    { label: "192", value: "Sudan", "enShortName": "SD" },
    { label: "193", value: "Suriname", "enShortName": "SR" },
    { label: "194", value: "Swaziland", "enShortName": "SZ" },
    { label: "195", value: "Sweden", "enShortName": "SE" },
    { label: "196", value: "Switzerland", "enShortName": "CH" },
    { label: "197", value: "Syria", "enShortName": "SY" },
    { label: "198", value: "Tajikistan", "enShortName": "TJ" },
    { label: "199", value: "Tanzania", "enShortName": "TZ" },
    { label: "200", value: "Thailand", "enShortName": "TH" },
    { label: "201", value: "Trinidad and Tobago", "enShortName": "TT" },
    { label: "202", value: "Timor-Leste", "enShortName": "TL" },
    { label: "203", value: "Togo", "enShortName": "TG" },
    { label: "204", value: "Tokelau", "enShortName": "TK" },
    { label: "205", value: "Tonga", "enShortName": "TO" },
    { label: "206", value: "Tunisia", "enShortName": "TN" },
    { label: "207", value: "Turkey", "enShortName": "TR" },
    { label: "208", value: "Turkmenistan", "enShortName": "TM" },
    { label: "209", value: "Tuvalu", "enShortName": "TV" },
    { label: "210", value: "Uganda", "enShortName": "UG" },
    { label: "211", value: "Ukraine", "enShortName": "UA" },
    { label: "212", value: "United Arab Emirates", "enShortName": "AE" },
    { label: "213", value: "United Kingdom", "enShortName": "UK" },
    { label: "214", value: "United States", "enShortName": "US" },
    { label: "215", value: "Uruguay", "enShortName": "UY" },
    { label: "216", value: "Uzbekistan", "enShortName": "UZ" },
    { label: "217", value: "Vanuatu", "enShortName": "VN" },
    { label: "218", value: "Vatican City", "enShortName": "VA" },
    { label: "219", value: "Venezuela", "enShortName": "VE" },
    { label: "220", value: "Vietnam", "enShortName": "VN" },
    { label: "221", value: "Wallis and Futuna", "enShortName": "WF" },
    { label: "222", value: "Western Sahara", "enShortName": "EH" },
    { label: "223", value: "Yemen", "enShortName": "YE" },
    { label: "224", value: "Yugoslavia", "enShortName": "YU" },
    { label: "225", value: "Zambia", "enShortName": "ZM" }, { label: "226", value: "Zimbabwe", "enShortName": "ZW" }
  ]
}
